# Generated by Django 5.1.5 on 2025-01-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_profile_is_private_profile_role_activitylog_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
