# Generated by Django 5.1.5 on 2025-01-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
